#!/usr/bin/env bash

############################################################################
##                                                                        ##
## Simple bash script that, given a file with passwords (each of them in  ##
## one separated by a line break) returns those that are repeated and how ##
## many times they are repeated.                                          ##
##                                                                        ##
############################################################################

function help {
echo "[x]Usage => repeatPasswords <file> "
}

if [[ ! -f $1 ]] || [[ $# -gt 1 ]];then
help
exit 255
fi

echo -e "[!]File: $1"

for i in $(cat $1)
do

times=$(cat $1 | grep $i | wc -l)
report=0
if [[ $times > 1 ]]; then
echo -e "\nPassword $i repeat $times times"
report=$(($report+1))
fi
done

echo "[!]Found $report matches"
echo "[!]DONE"
