#!/usr/bin/env bash

############################################################################
##                                                                        ##
## Simple bash script that, given a file with passwords (each of them in  ##
## one separated by a line break) returns those that are repeated and how ##
## many times they are repeated.                                          ##
##                                                                        ##
############################################################################

function help {
echo "[x]Usage => repeatPasswords <file> "
}

if [[ ! -f $1 ]] || [[ $# -gt 1 ]];then
help
exit 255
fi

report=0
echo -e "[!]File: $1\n"

for i in $(cat $1)
do

times=$(cat $1 | grep $i | wc -l)
if [[ $times > 1 ]]; then
echo -e "\t[*]Password repeat $times times \n"
report=$(($report+1))
fi
done

echo -e "[!]Found $report matches"
echo "[!]DONE"
