#!/bin/bash

clear

OS=$( awk -F "'" '/^menuentry/ {print "\x22","\b"$2,"\b\x22"}' /boot/grub/grub.cfg | wc -l)
minimal_OS=1
echo "##########################################################################"
echo "##								        ##"
echo "## Welcome to grub selector!                                            ##"
echo "## grub-selector is an  script in order to select the next OS to boot   ##"
echo "## author : aleph8                                                      ##"
echo "##                                                                      ##"
echo "##########################################################################"
echo

echo "Current available OS: "
echo

awk -F "'" '/^menuentry/ {print "\x22","\b"$2,"\b\x22"}' /boot/grub/grub.cfg

echo -e "\nSelect an OS ( 1 for the first and $OS for the last): "
read selected_OS

while [ $selected_OS -gt $OS ] || [ $selected_OS -lt $minimal_OS ]
do
	echo -e "\nSelect an OS ( 1 for the first and $OS for the last): "
        read selected_OS
done

echo -e "\n\nPress any key to reboot"
read confirmation
sudo grub-reboot $selected_OS
sudo reboot now
