#!/bin/env bash

##########################################################################
### aleph                                                              ###
###--------------------------------------------------------------------###
### Description                                                        ###
###                                                                    ###
### A simple script in order to lock the shell                         ###
###                                                                    ###
###--------------------------------------------------------------------###
###                                                                    ###
##########################################################################

signal_handler(){
echo "You can't do that"
}

trap signal_handler SIGINT SIGKILL SIGTSTP

pwd=000000
while [[ $pwd != 123456 ]]
do
read -s -p "Insert password in order to unlock the terminal: " pwd
clear
done

trap - SIGINT SIGKILL SIGTSTP
